name: vreasy-test
services:
  nginx:
    image: nginx:stable-alpine
    container_name: vreasy_test_nginx
    ports:
      - ${HTTP_PORT}:80
    volumes:
      - ./nginx/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ../:/var/www/html
    networks:
      - vreasy-test-network
  php-fpm:
    build:
      dockerfile: ./php-fpm/Dockerfile
      target: prod
    container_name: vreasy_test_app
    volumes:
      - ../:/var/www/html
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - vreasy-test-network
  mysql:
    image: mysql:9
    container_name: vreasy_test_db
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - ${MYSQL_PORT}:${DB_PORT}
    volumes:
      - vreasy-test-db:/var/lib/mysql
      - ./mysql/etc/mysql/conf.d/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    networks:
      - vreasy-test-network
volumes:
  vreasy-test-db:
networks:
  vreasy-test-network: